import { ScripturePreference } from "../ScripturePreference/ScripturePreference";
import { ScriptureLimitIndicator } from "../ScriptureLimitIndicator/ScriptureLimitIndicator";
import {
  T_TranslationConstructorParametersJSON,
  Translation,
} from "@/types/classes/model/Translation/Translation/Translation";
import {
  T_ScriptureCode,
  T_OriginalScriptureTextFontOfScriptureWithCodeT,
  T_OriginalScriptureTextFont,
} from "@/types/types";
import { VocalizationSymbols } from "@/util/textVariation";
import { ChapterLimitIndicator } from "../../Chapter/ChapterLimitIndicator/ChapterLimitIndicator";
import { SectionLimitIndicator } from "../../Section/SectionLimitIndicator/SectionLimitIndicator";

export abstract class ScriptureHelper {
  protected abstract readonly _number: number;
  protected abstract readonly _defaultTranslationId: number;
  protected abstract readonly _code: T_ScriptureCode;
  protected abstract readonly _vocalization: VocalizationSymbols;
  protected abstract readonly _defaultScriptureFont: T_OriginalScriptureTextFontOfScriptureWithCodeT;

  protected abstract readonly _translations: ReadonlyArray<Translation>;
  protected abstract _limiter?: Readonly<ScriptureLimitIndicator>;

  getTranslations(): ReadonlyArray<Translation> {
    return Object.freeze([...this._translations]);
  }

  getSelectedTranslations(preference: ScripturePreference) {
    return this.getTranslations().filter((t) =>
      preference.getPreferredTranslationIdMultiple().has(t.getId())
    );
  }

  getCode(): T_ScriptureCode {
    return this._code;
  }

  getNumber(): number {
    return this._number;
  }

  getDefaultTranslationId(): number {
    return this._defaultTranslationId;
  }

  getVocalizationSymbols(): Readonly<VocalizationSymbols> {
    return this._vocalization;
  }

  getDefaultTranslationFont(): Readonly<T_OriginalScriptureTextFont> {
    return this._defaultScriptureFont;
  }

  getLimiter() {
    if (!this._limiter) {
      this._limiter = this.loadLimiter();
    }
    return this._limiter;
  }

  protected abstract loadLimiter(): ScriptureLimitIndicator;

  isSectionExists(sectionNumber: number) {
    return sectionNumber <= this.getLimiter().getSectionLimiterCount();
  }

  isChapterExist(sectionNumber: number, chapterNumber: number) {
    const sectionLimiter =
      this.getLimiter().getNthSectionLimiter(sectionNumber);

    if (sectionLimiter === undefined) return false;

    return sectionLimiter.isChapterExists(chapterNumber);
  }

  isVerseExist(
    sectionNumber: number,
    chapterNumber: number,
    verseNumber: number
  ) {
    const sectionIndicator =
      this.getLimiter().getNthSectionLimiter(sectionNumber);

    if (sectionIndicator === undefined) return false;


    return sectionIndicator.isVerseExist(chapterNumber, verseNumber);
  }
}

export class TorahHelper extends ScriptureHelper {
  protected override _number: number = 1;
  protected override _defaultTranslationId: number = 1;
  protected override _code: T_ScriptureCode = "t";
  protected override _vocalization: VocalizationSymbols =
    new VocalizationSymbols({
      usual: "אָ֑",
      simplified: "א",
      withoutVowel: "א",
    });
  protected override _defaultScriptureFont: T_OriginalScriptureTextFontOfScriptureWithCodeT =
    "font-davidLibre";
  protected override _translations: readonly Translation[] =
    TORAH_TRANSLATIONS.map(Translation.createFromJSON);
  protected override _limiter?: Readonly<ScriptureLimitIndicator> = undefined; //Lazy Loading

  protected override loadLimiter(): ScriptureLimitIndicator {
    return new ScriptureLimitIndicator([
      new SectionLimitIndicator([
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(67),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(55),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(57),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(26),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(38),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(47),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(59),
        new ChapterLimitIndicator(57),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(55),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(34),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(54),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(89),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(45),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(65),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(39),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(54),
        new ChapterLimitIndicator(42),
        new ChapterLimitIndicator(56),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(13),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(69),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(52),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(12),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(63),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(45),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(33),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(57),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(48),
        new ChapterLimitIndicator(25),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(52),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(58),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(42),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(13),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(39),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(39),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(39),
        new ChapterLimitIndicator(25),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(53),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(66),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(54),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(30),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(24),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(34),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(63),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(35),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(10),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(21),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(15),
      ]),

      new SectionLimitIndicator([new ChapterLimitIndicator(21)]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(11),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(20),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(19),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(19),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(20),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(23),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(21),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(24),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(45),
        new ChapterLimitIndicator(48),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(2),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(176),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(4),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(3),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(3),
        new ChapterLimitIndicator(3),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(6),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(31),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(17),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(22),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(66),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(22),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(14),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(3),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(45),
        new ChapterLimitIndicator(13),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(70),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(44),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(72),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(47),
        new ChapterLimitIndicator(31),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(54),
        new ChapterLimitIndicator(55),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(66),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(47),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(30),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(42),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(23),
      ]),
    ]);
  }
}

const TORAH_TRANSLATIONS: Array<T_TranslationConstructorParametersJSON> = [
  {
    id: 1,
    name: "THE JPS TANAKH, 2023",
    language: {
      langCode: "en",
      langOwn: "English",
      langEnglish: "English",
    },
    translators: [
      {
        name: "Jewish Publication Society",
        url: null,
        language: {
          langCode: "en",
          langOwn: "English",
          langEnglish: "English",
        },
      },
    ],
    isEager: false,
  },
  {
    id: 2,
    name: "The Koren Jerusalim Bible",
    language: {
      langCode: "en",
      langOwn: "English",
      langEnglish: "English",
    },
    translators: [
      {
        name: "Koren Pub",
        url: null,
        language: {
          langCode: "en",
          langOwn: "English",
          langEnglish: "English",
        },
      },
    ],
    isEager: false,
  },
  {
    id: 3,
    name: "The Holy Scriptures: A New Translation, 1917",
    language: {
      langCode: "en",
      langOwn: "English",
      langEnglish: "English",
    },
    translators: [
      {
        name: "Jewish Publication Society",
        url: null,
        language: {
          langCode: "en",
          langOwn: "English",
          langEnglish: "English",
        },
      },
    ],
    isEager: false,
  },
] as const;
